### ISSUE TITLE
bubble plots not knitting

### ISSUE THREAD

**Issue by slager** [liannesheppard/ENVH556_2021course#11]
Hi Lianne,

I happened to see this comment just now, but I don't get automatically notified about comments on commits so I'm adding it as an issue here.

`For some reason the bubble plots are making the knit crash. R is complaining of a missing crs. Any ideas on how to fix this?`

To follow up, I've tested knitting on the plasmid and sph servers and I don't have problems with knitting the bubble plots.

**Comment by liannesheppard** [comment]
This is failing when run locally on my Macbook Air.  See attached screenshot.  

![Screen Shot 2021-02-23 at 11 22 49 AM](https://user-images.githubusercontent.com/12439598/108896298-94c8dc80-75c9-11eb-9a7e-20d4faee38a8.png)

I pushed the updated file to GitHub and will also test on the sph server.

**Comment by slager** [comment]
Maybe this is occurring because you're not using gstat version 2.0.7 or higher.  What do you see in your sessionInfo()?

**Comment by liannesheppard** [comment]
It is failing for me on the sph server too, in the same place.   (line 1091)
I'm using gstat version 2.0-6 both locally and on the sph server

**Comment by slager** [comment]
The issue is that gstat 2.0.6 drops the coordinate reference system during the kriging cv. So you'll need to install gstat 2.0.7 from github using the code at the beginning of the script.

If this gstat version thing is a problem (and maybe likely to be a problem for students as well) then perhaps I should just revert to using my wrapper function, so that the code will work with any gstat version.

**Comment by slager** [comment]
Thinking about it a little more, it seems like bringing back the wrapper function would save students the headache of struggling through installing different package versions. If you agree, I can go ahead and submit a PR with that fix.

**Comment by liannesheppard** [comment]
Yes, let's do it that way.  We can leave a comment in the document to clarify that this might only be a temporary fix.  However, I'm surprised that knitting the document didn't fix the problem given you put into the document the installation of the development version of gstat.

**Comment by slager** [comment]
Yeah, I'm not sure why it isn't installing the new version correctly. I thought the code I put in there would do it but I guess not. I'm glad you tested it on your computer and we found out it wasn't working before class!

**Comment by liannesheppard** [comment]
Thanks for addressing this.
