### ISSUE TITLE
Bad link in Week8LabGeostatistics.Rmd

### ISSUE THREAD

**Issue by brianhigh** [liannesheppard/ENVH556_2021course#5]
This link won't really work for most people.

```
Credit:  The following examples follow the code [here](http://127.0.0.1:18522/library/gstat/demo/krige.R).
```

**Comment by liannesheppard** [comment]
Thanks Brian for keeping in touch and paying attention.  Dave fixed this though now that we are using the sf package the credit may be obsolete.
